### ISSUE TITLE
State to text

### ISSUE THREAD

**Issue by test3210-d** [shlafik/eveuspro2ha#1]
`  value_template: "{%if state_attr('sensor.evse_eveus', 'state')==0 %} No data 
                        {% elif state_attr('sensor.evse_eveus', 'state')==1 %}Ready
                        {% elif state_attr('sensor.evse_eveus', 'state')==2 %}Wait
                        {% elif state_attr('sensor.evse_eveus', 'state')==3 %}Charge
                        {% elif state_attr('sensor.evse_eveus', 'state')==4 %}??
                        {% elif state_attr('sensor.evse_eveus', 'state')==5 %}??
                        {% elif state_attr('sensor.evse_eveus', 'state')==6 %} - 
                        {% elif state_attr('sensor.evse_eveus', 'state')==7 %}Leak
                        {% elif state_attr('sensor.evse_eveus', 'state')==8 %}Ground
                        {% elif state_attr('sensor.evse_eveus', 'state')==9 %}CPU err
                        {% elif state_attr('sensor.evse_eveus', 'state')==10 %}Plug owerheat
                        {% elif state_attr('sensor.evse_eveus', 'state')==11 %}Owerheat
                        {% elif state_attr('sensor.evse_eveus', 'state')==12 %}Owercurrent
                        {% elif state_attr('sensor.evse_eveus', 'state')==13 %}Owervoltage
                        {% elif state_attr('sensor.evse_eveus', 'state')==14 %}Low voltage
                        {% elif state_attr('sensor.evse_eveus', 'state')==15 %}Time limit
                        {% elif state_attr('sensor.evse_eveus', 'state')==16 %}Energy limit
                        {% elif state_attr('sensor.evse_eveus', 'state')==17 %}Cost limit
                        {% elif state_attr('sensor.evse_eveus', 'state')==18 %}Schedule 1 limit
                        {% elif state_attr('sensor.evse_eveus', 'state')==19 %}Schedule 2 limit
                        {% elif state_attr('sensor.evse_eveus', 'state')==20 %}Disabled by user
                        {% elif state_attr('sensor.evse_eveus', 'state')==21 %}Relay error
                        {% elif state_attr('sensor.evse_eveus', 'state')==22 %}AI mode limit
                        {% endif %}"
        friendly_name: "State"
`

**Comment by shlafik** [comment]
Used mapper instead of if-then-else
